# Generated by Django 5.1.4 on 2025-01-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
