# Generated by Django 5.1.4 on 2025-01-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="profile",
        ),
    ]
