# Generated by Django 5.1.4 on 2025-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
